import { describe, it, expect } from 'vitest';
import {
  sanitizeThermalText,
  encodeCp437,
  generateEscPosBytes,
} from '../utils/bluetoothPrinterHelper';

describe('bluetoothPrinterHelper — Edge Case #3 (CP437 Encoding & Character Sanitization)', () => {
  it('sanitizes smart quotes, dashes, and bullet points to safe ASCII', () => {
    const dirty = '“Kopi Enak” – Diskon • Spesial ‘Coba’ …';
    const clean = sanitizeThermalText(dirty);
    expect(clean).toBe('"Kopi Enak" - Diskon * Spesial \'Coba\' ...');
  });

  it('encodes ASCII text into single-byte array without multi-byte UTF-8 artifacts', () => {
    const text = 'Total: Rp 50.000\n';
    const bytes = encodeCp437(text);
    // Every byte must be single byte <= 0x7F or valid control code
    bytes.forEach((b) => {
      expect(b).toBeGreaterThanOrEqual(0);
      expect(b).toBeLessThanOrEqual(0xff);
    });
    // Check that length corresponds to character length
    expect(bytes.length).toBe(text.length);
  });

  it('includes ESC @ and ESC t 0 (CP437 code page selection) in generated byte stream', () => {
    const sampleOrder = {
      id: 1,
      transactionId: 'TRX-001',
      total: 10000,
      metode: 'Tunai',
      uangDiterima: 10000,
      kembalian: 0,
      items: [{ namaBarang: 'Kopi', qty: 1, hargaSatuan: 10000, total: 10000 }],
    };

    const bytes = generateEscPosBytes(sampleOrder);
    expect(bytes).toBeInstanceOf(Uint8Array);

    // Verify ESC @ ([0x1B, 0x40]) is at the beginning
    expect(bytes[0]).toBe(0x1b);
    expect(bytes[1]).toBe(0x40);

    // Verify ESC t 0 ([0x1B, 0x74, 0x00]) is present immediately after
    expect(bytes[2]).toBe(0x1b);
    expect(bytes[3]).toBe(0x74);
    expect(bytes[4]).toBe(0x00);
  });
});
