/**
 * Unit tests for storage.js
 *
 * Task 15.2: Verify that sessionId is stored and can be read back.
 *
 * Validates: Requirement 8.4
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  addTransaction,
  getTransactions,
} from './storage.js';

// ── Setup / Teardown ──────────────────────────────────────

beforeEach(() => {
  localStorage.clear();
});

afterEach(() => {
  localStorage.clear();
});

// ── Helpers ───────────────────────────────────────────────

function makeTransactionData(overrides = {}) {
  return {
    tanggal: '2025-07-14',
    kategori: 'Elektronik',
    subKategori: '',
    namaBarang: 'Test Barang',
    qty: 2,
    hargaSatuan: 10000,
    total: 20000,
    metode: 'Tunai',
    catatan: '',
    kasir: 'Admin',
    ...overrides,
  };
}

// ── Unit Tests ────────────────────────────────────────────

describe('addTransaction — sessionId persistence', () => {
  it('stores sessionId when provided and can be read back', () => {
    const sessionId = 'test-session-uuid-1234';
    const txData = makeTransactionData({ sessionId });

    const saved = addTransaction(txData);

    // The returned object must include sessionId
    expect(saved.sessionId).toBe(sessionId);

    // Reading back from storage must also include sessionId
    const all = getTransactions();
    expect(all.length).toBe(1);
    expect(all[0].sessionId).toBe(sessionId);
  });

  it('stores sessionId as null when not in active session', () => {
    const txData = makeTransactionData({ sessionId: null });

    const saved = addTransaction(txData);

    expect(saved.sessionId).toBeNull();

    const all = getTransactions();
    expect(all[0].sessionId).toBeNull();
  });

  it('stores sessionId as null when sessionId field is omitted', () => {
    // No sessionId field in the transaction data
    const txData = makeTransactionData();
    // Ensure sessionId is not present
    delete txData.sessionId;

    const saved = addTransaction(txData);

    // sessionId should be undefined (not present) — not null, but also not a UUID
    // The spread preserves whatever was in the input
    expect(saved.sessionId).toBeUndefined();

    const all = getTransactions();
    expect(all[0].sessionId).toBeUndefined();
  });

  it('preserves sessionId across multiple transactions', () => {
    const sessionId = 'session-abc-123';

    addTransaction(makeTransactionData({ sessionId, namaBarang: 'Barang 1' }));
    addTransaction(makeTransactionData({ sessionId, namaBarang: 'Barang 2' }));
    addTransaction(makeTransactionData({ sessionId: null, namaBarang: 'Barang 3' }));

    const all = getTransactions();
    expect(all.length).toBe(3);

    // Transactions are stored newest-first (unshift)
    const withSession = all.filter((tx) => tx.sessionId === sessionId);
    const withoutSession = all.filter((tx) => tx.sessionId === null);

    expect(withSession.length).toBe(2);
    expect(withoutSession.length).toBe(1);
  });

  it('immutable fields are not overwritten by sessionId spread', () => {
    const sessionId = 'session-xyz-789';
    const txData = makeTransactionData({ sessionId });

    const saved = addTransaction(txData);

    // Immutable fields must be generated by addTransaction, not from input
    expect(typeof saved.id).toBe('number');
    expect(saved.transactionId).toMatch(/^TRX-\d{5}$/);
    expect(typeof saved.createdAt).toBe('string');
    expect(saved.status).toBe('Selesai');

    // sessionId must still be preserved
    expect(saved.sessionId).toBe(sessionId);
  });
});
